const CONFIG = {
    titleWeb: "Quýnh lộn đeee",
    introTitle: 'Hello bạn',
    introDesc: `Mình có điều muốn hỏi bạn`,
    btnIntro: 'Lét gô',
    title: 'Bạn có thích mình hơm',
    desc: 'hehehe',
    btnYes: 'Có',
    btnNo: 'Không nha :3',
    question: 'Lý do gỳ bạn thích mình dạ ',
    btnReply: 'Gửi cho bạn',
    reply: 'tại bạn dễ thương á',
    mess: 'Dị hả mình biêt mà, mình cũng thích mình lớm',
    messDesc: '',
    btnAccept: 'Hehe',
    messLink: 'https://www.facebook.com/shmiljm/'
